//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saleslogix.Social.Mashups.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saleslogix.Social.Mashups.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation.
        /// </summary>
        internal static string AggregateProcessor_AggregationSingular {
            get {
                return ResourceManager.GetString("AggregateProcessor_AggregationSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string AggregateProcessor_GroupSingular {
            get {
                return ResourceManager.GetString("AggregateProcessor_GroupSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type specified.
        /// </summary>
        internal static string Aggregation_InvalidTypeSpecified {
            get {
                return ResourceManager.GetString("Aggregation_InvalidTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute query:.
        /// </summary>
        internal static string DefaultQueryExecutor_UnableToExecuteQuery {
            get {
                return ResourceManager.GetString("DefaultQueryExecutor_UnableToExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type specified.
        /// </summary>
        internal static string FeedProcessor_InvalidTypeSpecified {
            get {
                return ResourceManager.GetString("FeedProcessor_InvalidTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected feed content:.
        /// </summary>
        internal static string FeedProcessor_UnexpectedFeedContent {
            get {
                return ResourceManager.GetString("FeedProcessor_UnexpectedFeedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri &apos;{0}&apos; is not well formed.
        /// </summary>
        internal static string FeedProcessor_UriNotWellFormed {
            get {
                return ResourceManager.GetString("FeedProcessor_UriNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string InputProcessorBase_ParameterSingular {
            get {
                return ResourceManager.GetString("InputProcessorBase_ParameterSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; not found.
        /// </summary>
        internal static string JoinProcessor_InputNotFound {
            get {
                return ResourceManager.GetString("JoinProcessor_InputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type specified.
        /// </summary>
        internal static string JoinProcessor_InvalidTypeSpecified {
            get {
                return ResourceManager.GetString("JoinProcessor_InvalidTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join &apos;{0}&apos; not found.
        /// </summary>
        internal static string JoinProcessor_JoinNotFound {
            get {
                return ResourceManager.GetString("JoinProcessor_JoinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string JoinProcessor_JoinSingular {
            get {
                return ResourceManager.GetString("JoinProcessor_JoinSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id to display updates from.  Note this is the LinkedIn internal user id (a short alphanumeric string), NOT the user&apos;s name or email address.
        /// </summary>
        internal static string Linkedin_LinkedInUser_Description {
            get {
                return ResourceManager.GetString("Linkedin_LinkedInUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn Processor.
        /// </summary>
        internal static string LinkedinProcessor_DisplayName {
            get {
                return ResourceManager.GetString("LinkedinProcessor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job Posting: {0} ({1}).  {2}.
        /// </summary>
        internal static string LinkedinProcessor_NewJob {
            get {
                return ResourceManager.GetString("LinkedinProcessor_NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to the company products page: {0}.
        /// </summary>
        internal static string LinkedinProcessor_NewProduct {
            get {
                return ResourceManager.GetString("LinkedinProcessor_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed position to {1}.
        /// </summary>
        internal static string LinkedProcessor_ChangedPosition {
            get {
                return ResourceManager.GetString("LinkedProcessor_ChangedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was hired as {1}.
        /// </summary>
        internal static string LinkedProcessor_NewHire {
            get {
                return ResourceManager.GetString("LinkedProcessor_NewHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; already exists.
        /// </summary>
        internal static string Mashup_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Mashup_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; contains invalid characters.
        /// </summary>
        internal static string Mashup_NameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Mashup_NameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Mashup_ParameterSingular {
            get {
                return ResourceManager.GetString("Mashup_ParameterSingular", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MashupImage {
            get {
                object obj = ResourceManager.GetObject("MashupImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mashup {0}.
        /// </summary>
        internal static string MashupModel_NewMashupName {
            get {
                return ResourceManager.GetString("MashupModel_NewMashupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashup &apos;{0}&apos; not found.
        /// </summary>
        internal static string MashupProcessor_MashupNotFound {
            get {
                return ResourceManager.GetString("MashupProcessor_MashupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent mashup has not been added to a mashup container.
        /// </summary>
        internal static string MashupProcessor_ParentMashupNotAddedToContainer {
            get {
                return ResourceManager.GetString("MashupProcessor_ParentMashupNotAddedToContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor has not been added to a mashup.
        /// </summary>
        internal static string MashupProcessor_ProcessorNotAddedToMashup {
            get {
                return ResourceManager.GetString("MashupProcessor_ProcessorNotAddedToMashup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result &apos;{0}&apos; not found.
        /// </summary>
        internal static string MashupProcessor_ResultNotFound {
            get {
                return ResourceManager.GetString("MashupProcessor_ResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate &apos;{0}&apos; processor:.
        /// </summary>
        internal static string ProcessorBase_UnableToValidateProcessor {
            get {
                return ResourceManager.GetString("ProcessorBase_UnableToValidateProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        internal static string PropertyCannotBeEmpty {
            get {
                return ResourceManager.GetString("PropertyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Processor.
        /// </summary>
        internal static string TwitterProcessor_DisplayName {
            get {
                return ResourceManager.GetString("TwitterProcessor_DisplayName", resourceCulture);
            }
        }
    }
}
